#!/bin/bash

set -e
script/fmt
script/kestrel
set +e

GOPATH=`pwd`/.gopack/vendor go test
exit=$?

# Cleanup
kill $(cat tmp/kestrel.pid) > /dev/null 2>&1

# But always exit with the status code of the test run
exit $exit
